name: kustasoft_store_checker
# uzun 60-180 aras açıklama
description: "A Flutter plugin to check the origin of the installed app, whether from App Store or TestFlight."
version: 1.0.2
homepage: https://github.com/kustasoft/kustasoft_store_checker
repository: https://github.com/kustasoft/kustasoft_store_checker/tree/master
issue_tracker: https://github.com/kustasoft/kustasoft_store_checker/issues

environment:
  sdk: ^3.7.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.kustasoft.kustasoft_store_checker
        pluginClass: KustasoftStoreCheckerPlugin
      ios:
        pluginClass: KustasoftStoreCheckerPlugin
      macos:
        pluginClass: KustasoftStoreCheckerPlugin
